#!/usr/bin/env python3
"""Unit tests for the pure half of scripts/contracts.py.

The network half cannot be tested without a venue, and a test that needs
Polymarket to be up is a test that fails for reasons unrelated to this
repo. What is testable is the parsing and the date arithmetic, which is
also where a silent wrong answer would do the most damage: a registry
reader that quietly finds zero tokens reports "no tokens found" rather
than "all dead", and those need to stay distinguishable.

Run: python3 tests/test_contracts_script.py
"""

import importlib.util
import pathlib
import sys
import tempfile
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("contracts", ROOT / "scripts" / "contracts.py")
contracts = importlib.util.module_from_spec(spec)
spec.loader.exec_module(contracts)

failures = 0


def check(cond, label):
    global failures
    if cond:
        print(f"  ok   {label}")
    else:
        print(f"  FAIL {label}")
        failures += 1


def write(text):
    f = tempfile.NamedTemporaryFile("w", suffix=".toml", delete=False, encoding="utf-8")
    f.write(text)
    f.close()
    return f.name


print("contracts.py unit tests")

# read_registry pairs each token with the id of the event it belongs to,
# which is what makes the check output name the dead contract rather than
# just counting them.
path = write('''
[[event]]
id = "alpha"
polymarket_token = "111"
polymarket_no_token = "999"

[[event]]
id = "beta"
basket = "b"
polymarket_token = "222"
''')
pairs = contracts.read_registry(path)
check(pairs == [("alpha", "111"), ("beta", "222")],
      f"read_registry pairs ids with YES tokens, ignoring NO tokens: {pairs}")

# An event with no Polymarket token is skipped rather than paired with the
# next event's token, which is the off-by-one this ordering invites.
path = write('''
[[event]]
id = "kalshi-only"
kalshi = "SOME-TICKER"

[[event]]
id = "gamma"
polymarket_token = "333"
''')
pairs = contracts.read_registry(path)
check(pairs == [("gamma", "333")],
      f"an event without a token does not steal the next one's: {pairs}")

check(contracts.read_registry(write("# nothing here\n")) == [],
      "a registry with no tokens reads as empty, not as an error")

# The generation stamp is what distinguishes a generated registry from a
# hand-written one, so the check can report age for the first and say so
# for the second.
check(contracts.generated_on(
    "# generated by scripts/contracts.py on 2026-08-29 from clob") == "2026-08-29",
    "generated_on finds the stamp a refresh writes")
check(contracts.generated_on("# written by a person\n") is None,
      "generated_on returns None for a hand-written file")

today = time.strftime("%Y-%m-%d", time.gmtime())
check(contracts.age_days(today) == 0, "age_days is 0 for today")
check(contracts.age_days("2026-08-01") > 0, "age_days is positive for the past")

print(f"\n{'PASS' if failures == 0 else 'FAIL'}  {failures} failure(s)")
sys.exit(1 if failures else 0)
